version: '3'

services:
  # database:
  #   image: postgres
  #   container_name: pg_container
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #   - $HOME/docker/volumes/postgres/kartify:/var/lib/postgresql/data

  web:
    image: scoronelhamilton/web-server:5
    container_name: web-server
    ports: 
      - '3000:80'
    # restart: on-failure
    # links:
    #   - database
    environment:
      - PGUSER=postgres
      - PGPASSWORD=kartify
      - PGDATABASE=kartify
      - PGHOST=3.90.7.137
      - PGPORT=5432

