version: '3'

services:
  database:
    image: postgres
    container_name: pg_container
    ports:
      - '5432:5432'
    volumes:
      # - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  web:
    build: .
    container_name: web-server
    ports: 
      - '80:80'
    restart: on-failure
    depends_on:
     - database
    # depends_on:
    #   - database
    environment:
      # - PGPASSWORD=password
      - PGUSER=postgres
      - PGDATABASE=kartify
      - PGHOST=database
      - PGPORT=5432


   


  


  

