-- Table 'Questions'

CREATE TABLE IF NOT EXISTS `Questions` (
  `id` INTEGER NOT NULL AUTO_INCREMENT DEFAULT NULL,
  `product_id` INTEGER NOT NULL DEFAULT NULL,
  `asker_name` VARCHAR(40) NOT NULL DEFAULT 'NULL',
  `body` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `helpful` SMALLINT NULL DEFAULT NULL,
  `reported` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- Table 'Answers'
		
CREATE TABLE IF NOT EXISTS `Answers` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `question_id` INTEGER NOT NULL DEFAULT NULL,
  `answer_name` VARCHAR(40) NULL DEFAULT NULL,
  `body` VARCHAR(255) NOT NULL DEFAULT 'NULL',
  `date` DATETIME NULL DEFAULT NULL,
  `helpful` SMALLINT NULL DEFAULT NULL,
  `reported` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- Table 'Photos'
		
CREATE TABLE IF NOT EXISTS `Photos` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `answer_id` INTEGER NOT NULL DEFAULT NULL,
  `url` VARCHAR(2047) NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

-- Foreign Keys 

ALTER TABLE `Answers` ADD FOREIGN KEY (question_id) REFERENCES `Questions` (`id`);
ALTER TABLE `Photos` ADD FOREIGN KEY (answer_id) REFERENCES `Answers` (`id`);

-- Table Properties

ALTER TABLE `Questions` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `Answers` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `Photos` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;